audit_header: false
title: Fort Wayne Real Estate Video Blog with David Brough
description: Our mission at Anthony REALTORS is to be your best resource for Fort Wayne real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Anthony REALTORS, your professional Fort Wayne Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: David Brough
  title:
  license_number:
  about_markdown: |
    The entrepreneurial spirit is deeply-rooted in my family. My father was a small business owner, and I'm the youngest of 5 brothers and sisters. I suppose you could say all of us have the same ‘fire’ for starting something great, and creating a business from the ground up, as we’re all self-employed in some way. My passion? Real estate. It’s been that way since I was young, and it’s something I’ve carried with me my entire life. Thankfully, I’ve been able to live out that passion for the past 10 years as a Realtor and home renovator, watching the market completely shift, seeing buying trends change, and even working through the “Great Recession.” I started Anthony REALTORS out of my basement in 2012 and today we are a team of high quality individuals operating out of the Historic Baker Street Station in downtown Fort Wayne.
  market: Fort Wayne
  brand: Anthony REALTORS
  brokerage:
  address: 239 West Baker Street<br>Fort Wayne, IN 46802
  phone: 260-627-9337
  phone_type:
  phone2:
  phone2_type:
  email: info@anthonyrealtors.com
  url: http://www.fortwaynehomehub.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.fortwaynehomehub.com/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.fortwaynehomehub.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Fort Wayne Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.fortwaynehomehub.com/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Fort Wayne Home?"
    CTA_text2: "Search the entire MLS for your Fort Wayne home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.fortwaynehomehub.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url: https://www.linkedin.com/in/david-brough-a9770654/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCpjAigMjJwdpDeXr1hAS72w
  twitter_url: https://twitter.com/davidbrough
  instagram_url: https://www.instagram.com/anthonyrealtors/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Fort Wayne Real Estate Podcast with David Brough'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Fort Wayne Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Anthony REALTORS - your professional Fort Wayne Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Fort Wayne, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'David Brough'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Fort Wayne Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#89c251'
  theme_color: '#515151'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
